#Tests
pipeline:
  clone:
    image: plugins/git
    depth: 1
  basetest-linux:
    image: build-lazarus-x64:latest
    stage: test 
    commands:
      - promet/source/testcases/build.sh
  webdavtest-linux:
    image: build-lazarus-x64:latest
    stage: test 
    commands: 
      - promet/source/testcases/build_webdav.sh

#mysql-test:
#  image: build-lazarus-x64:latest
#  services:
#    - mysql:latest
#  variables:
#    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
#    MYSQL_DATABASE: promet
#    MYSQL_USER: promet
#    MYSQL_ROOT_PASSWORD: password
#  stage: test 
#  script:  
#    - sudo apt-get install -y mysql-client libmysqlclient-dev
#    - lazbuild promet/source/testcases/consoletest.lpi
#    - promet/output/x86_64-linux/consoletest --mandant=help --config-path=./promet/help/config
#  tags:
#    - docker-lazarus-x64
#  allow_failure: true
#firebird-test:
#  image: build-lazarus-x64:latest
#  services:
#    - mysql:latest
#  variables:
#    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
#    ISC_USER: promet
#    ISC_PASSWD: password
#  stage: test 
#  script:  
#    - sudo apt-get install -y mysql-client libmysqlclient-dev
#    - lazbuild promet/source/testcases/consoletest.lpi
#    - promet/output/x86_64-linux/consoletest --mandant=help --config-path=./promet/help/config
#  tags:
#    - docker-lazarus-x64
#  allow_failure: true
#Build
#build:windows:
#  stage: build 
#  variables:
#  script: 
#    - git submodule sync --recursive
#    - bash build.sh clean
#    - bash build.sh all
#  tags:
#    - windows-i386
#  only:
#    - master
#  artifacts:
#    paths:
#      - promet/setup/output
#    expire_in: 1 week  

#build:linux:i386:
#  image: build-lazarus-i386
#  stage: build 
#  script: 
#    - bash build.sh clean
#    - bash build.sh all
#  tags:
#    - docker-lazarus-x64
#  only:
#    - master
#  artifacts:
#    paths:
#      - promet/setup/output
#    expire_in: 1 week  

#build:linux:x86-64:
#  image: build-lazarus-x64:latest
#  stage: build 
#  script: 
#    - bash build.sh clean
#    - bash build.sh all
#  tags:
#    - docker-lazarus-x64
#  only:
#    - master
#  artifacts:
#    paths:
#      - promet/setup/output
#    expire_in: 1 week  

#build:linux:arm:
#  variables:
#    GIT_DEPTH: ""
#  before_script:
#    - git submodule sync
#    - git submodule foreach git submodule update
#    - git submodule update --init --recursive
#  stage: build 
#  script:
#    - git clean -fdx
#    - git submodule foreach git reset --hard
#    - bash build.sh server
#  tags:
#    - linux-arm
#  only:
#    - master
#  artifacts:
#    paths:
#      - promet/setup/output
#    expire_in: 1 week  
#  allow_failure: true      

#upload:all:
#  before_script:
#    - git submodule sync --recursive
#    - git submodule update --init --recursive
#    - ls -l promet/setup/output/*
#  stage: upload
#  script:
#    - bash promet/setup/upload_builds.sh
#  only:
#    - master
#  dependencies:
#    - build:linux:arm
#    - build:linux:i386
#    - build:linux:x86-64
 #   - build:windows
#  artifacts:
#    paths:
#      - promet/setup/output/act_alphadownload.txt
#    expire_in: 1 week
#  tags:
#    - linux-x64

#update:containers:
#  before_script:
#    - ls -l promet/setup/output/*
#  stage: publish
#  script:
#    - bash promet/setup/build_containers.sh
#  dependencies:
#    - upload:all
#  only:
#    - master
#  tags:
#    - linux-x64
#  allow_failure: true
#update:alpha-wiki:
#  image: build-lazarus-x64:latest
#  before_script:
#    - ls -l promet/setup/output/*
#  stage: publish
#  script:
#    - bash promet/setup/change_wiki_alpha.sh
#  only:
#    - master
#  dependencies:
#    - upload:all
#  tags:
#    - docker-lazarus-x64
#  allow_failure: true
#deploy:new_version:
#  before_script:
#    - ls -l
#  script:
#    - bash promet/setup/change_wiki_version.sh
#  tags:
#    - linux-x64
#  only:
#  - tags
