workspace:
  path: src/gogs/promet-erp
#Tests
pipeline:
  clone:
    image: plugins/git
    depth: 10
    recursive: true
    submodule_update_remote: true
  basetest-linux:
    image: build-lazarus-x64:latest
    stage: test 
    commands:
      - promet/source/testcases/build.sh
  webdavtest-linux:
    image: build-lazarus-x64:latest
    stage: test 
    commands: 
      - promet/source/testcases/build_webdav.sh
  build-linux-i386:
    image: build-lazarus-i386
    stage: build 
    commands: 
      - bash build.sh clean
      - bash build.sh all
#    when:
#      - master
  build-linux-x86-64:
    image: build-lazarus-x64:latest
    stage: build 
    commands: 
      - bash build.sh clean
      - bash build.sh all
#    when:
#      - master